name: 部署到GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      force_deploy:
        description: '强制部署（即使没有更改）'
        required: false
        default: false
        type: boolean
  schedule:
    # 每天UTC时间16:30 (对应北京时间00:30)
    - cron: '30 16 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 设置Node.js环境
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: 安装依赖
        run: npm ci
      
      - name: 构建静态网站
        run: |
          mkdir -p dist
          node scripts/build-gh-pages.js
      
      - name: 验证构建
        run: node scripts/verify-build.js
      
      - name: 设置Pages
        uses: actions/configure-pages@v3
      
      - name: 上传构建结果
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'
      
      - name: 上传构建日志
        uses: actions/upload-artifact@v2
        with:
          name: build-logs
          path: |
            npm-debug.log*
            yarn-debug.log*
            yarn-error.log*
          retention-days: 3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署到GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 