name: 部署免费节点抓取工具到GitHub Pages

on:
  # 自动执行的时间，北京时间00:30运行
  schedule:
    - cron: '30 16 * * *'
  
  # 当push到main分支时也执行
  push:
    branches: [ main ]
  
  # 允许手动触发工作流
  workflow_dispatch:

# 设置权限
permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 检出仓库代码
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0
        
      # 设置Node.js环境
      - name: 设置Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      # 安装依赖
      - name: 安装依赖
        run: npm install
        
      # 执行抓取和生成静态网站
      - name: 生成静态网站
        run: node generate-static.js
        
      # 部署到GitHub Pages
      - name: 部署到GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist      # 使用dist目录作为源目录
          branch: gh-pages  # 部署到gh-pages分支
          clean: true       # 清理旧文件
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # 提交最新数据到主分支
      - name: 提交最新数据
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/*.json
          git diff --quiet && git diff --staged --quiet || git commit -m "自动更新: 更新节点数据 [skip ci]"
          git push --set-upstream origin main || (git pull --rebase origin main && git push) 