name: 部署到GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
  schedule:
    # 每天UTC时间16:30 (对应北京时间00:30)
    - cron: '30 16 * * *'

# 设置必要的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 允许一次只运行一个部署
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: 安装依赖
        run: npm install
      
      - name: 构建静态网站
        run: |
          mkdir -p dist
          node scripts/build-gh-pages.js
      
      - name: 验证构建
        run: node scripts/verify-build.js
      
      - name: 确保所有必要文件都被包含
        run: |
          # 列出构建目录中的所有文件
          echo "构建目录内容："
          find ./dist -type f | sort
          
          # 确保data和json目录存在
          echo "确保数据目录存在..."
          mkdir -p ./dist/data
          mkdir -p ./dist/json
          
          # 列出data目录文件
          echo "data目录文件："
          ls -la ./dist/data || echo "data目录为空"
          
          # 列出json目录文件
          echo "json目录文件："
          ls -la ./dist/json || echo "json目录为空"
      
      - name: 设置Pages
        uses: actions/configure-pages@v4
      
      - name: 上传Pages构建结果
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  # 部署工作
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署到GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 